### ISSUE TITLE
Integration crashes if not all waste types listed

### ISSUE THREAD

**Issue by flabbamann** [flabbamann/aha_region#30]
At some addresses not all waste types are collected, this leads to errors, as the integration expects all waste types to be listed.

Example config where only `Papier` and `Leichtverpackungen` are collected:

```yaml
sensor:
  - platform: aha_region
    gemeinde: "Hannover"
    strasse: "00726@Dragonerstr. / Vahrenwald@Vahrenwald"
    hausnr: 35
    abholplatz: "00726-0037B" 
```
