### ISSUE TITLE
Days to collection Sensor

### ISSUE THREAD

**Issue by torsti09** [flabbamann/aha_region#51]
Hey!
First of all, thanks for this nice integration.

I've build a sensor in configuration for display how many days until colletion date.
Feel free to use it, too.

```
template:
  - sensor:
      - name: "Abholung Restmüll"
        unique_id: "abholung_restmuell"
        unit_of_measurement: "Days"
        icon: mdi:trash-can
        state: >
            {% set days_to = (((as_timestamp(strptime(states('sensor.restabfall'), "%Y-%m-%d")))  - as_timestamp(now())) / 86400) | round(default=0) %}
            {% if days_to == 0 %}Heute{% elif days_to == 1 %}Morgen{% else %}in {{days_to}} Tagen{% endif %}
```

Greetings
torsti09

**Comment by Arnerei** [comment]
Hey torsti09,
thanks for your blueprint.
I adjusted it for my case. 

````
 - platform: template
    sensors:
      countdown_restmuell:
        friendly_name: "Abholung Restmüll"
        value_template: >
            {% set days_to = (((as_timestamp(strptime(states('sensor.restabfall'), "%Y-%m-%d")))  - as_timestamp(now())) / 86400) | round(default=0) %}
            {% if days_to == 0 %}Heute{% elif days_to == 1 %}Morgen{% else %}in {{days_to}} Tagen{% endif %}
````

Cheers
Arnerei
